config/routes.rb
PersonalSite::Application.routes.draw do

  root 'pages#index'

  match "/about", to: "pages#about", as: :about, via: :get
  match "/education", to: "pages#education", as: :education, via: :get
  match "/courses", to: "projects#courses", as: :courses, via: :get
  match "/hackathons", to: "projects#hackathons", as: :hackathons, via: :get
  match "/portfolio", to: "projects#portfolio", as: :portfolio, via: :get
  match "/blog", to: "posts#index", as: :blog, via: :get
  match "/miscellaneous", to: "pages#miscellaneous", as: :miscellaneous, via: :get

  match "/github", to: redirect("https://github.com/RochesterinNYC"), as: :github, via: :get
  match "/linkedin", to: redirect("http://www.linkedin.com/in/jamesrwen"), as: :linkedin, via: :get
  match "/twitter", to: redirect("https://twitter.com/RochesterinNYC"), as: :twitter, via: :get
  match "/soundcloud", to: redirect("https://soundcloud.com/james-rochester-wen"), as: :soundcloud, via: :get

  resources :projects
  resources :posts
  resources :uploads

  get '/login', to: 'sessions#new', :as => "login"
  post '/verify', to: 'sessions#create', :as => 'verify'
  post '/logout', to: 'sessions#destroy', :as => 'logout'

  post '/markdown', to: 'projects#markdown', :as => 'markdown'
  post '/delete_attachment', to: 'projects#delete_attachment', :as => 'delete_attachment'
  post '/delete_file', to: 'uploads#delete_file', :as => 'delete_file'

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :handle, use: :slugged

  VALID_CATEGORIES = %w{ COURSE HACKATHON PERSONAL INACTIVE }

  has_attached_file :source_download, url: "/projects/:handle/:filename"

  validates :title, presence: true, uniqueness: true
  validates :handle, presence: true, uniqueness: true
  validates :description, presence: true
  validates :category, presence: true
  validates_inclusion_of :status, in: VALID_CATEGORIES
  #Create image delete methods
  [:source_download].each do |attachment|
    define_method("#{attachment}_delete".to_sym) { self.send("#{attachment}=", nil); self.save! }
  end

  #Create project category query and bang methods
  VALID_CATEGORIES.each do |category|
    scope category.to_s.downcase, -> { where(category: category) }
    define_method("#{category.downcase}?".to_sym) { self.category.to_s.upcase == category.to_s.upcase }
    define_method("#{category.downcase}!".to_sym) { self.category = category.to_s.upcase; self.save! }
  end

  def self.valid_categories
    VALID_CATEGORIES
  end

  def delete_attachment(attachment)
    self.send("#{attachment}_delete")
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :get_project, only: [:delete_attachment, :destroy, :edit, :show, :update]
  before_filter :require_user, only: [:create, :delete_attachment, :destroy, :edit, :index, :markdown, :new, :update]

  respond_to :html, :json

  def create
    @project = Project.create(project_params)
    if @project.save
      params[:source] = "ADMIN"
      redirect_to project_path(@project)
    else
      respond_with(@project) do |format|
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.html { render :new }
      end
    end
  end

  def delete_attachment
    @project.delete_attachment(params[:attachment])
    redirect_to edit_project_path(@project)
  end

  def destroy
    @project.destroy
    #flash[:success] = "Project was deleted."
    redirect_to projects_path
  end

  def edit
  end

  def index
    @projects = Project.order('priority').all
    params[:source] = "ADMIN"
  end

  def markdown
    html_content = PersonalSite::MARKDOWN.render(params[:markdown_content])
    render json: {html_content: html_content}
  end

  def new
    @project = Project.new
  end

  def show
  end

  def update
    if @project.update_attributes(project_params)
      params[:source] = "ADMIN"
      render :show
    else
      flash[:notice] = "Project not updated"
      render :edit
    end
  end

  def courses
    @title = "COURSE PROJECTS"
    @projects = Project.order('priority').course
    params[:source] = "COURSE"
  end

  def hackathons
    @title = "HACKATHON PROJECTS"
    @projects = Project.order('priority').hackathon
    params[:source] = "HACKATHON"
  end

  def portfolio
    @title = "PORTFOLIO PROJECTS"
    @projects = Project.order('priority').personal
    params[:source] = "PERSONAL"
  end

  protected
  def get_project
    @project = Project.friendly.find(params[:id])
  end

  private
  def project_params
    params.require(:project).permit(:category, :title, :handle, :modifier, :content, :description, :site_link, :github_link, :priority, :image1, :image1_file_name, :image2, :image2_file_name, :image3, :image3_file_name, :image4, :image4_file_name, :image5, :image5_file_name, :image6, :image6_file_name, :source_download)
  end

end

app/views/projects/_display.html.haml
- projects.each do |project|
  = render partial: 'projects/project', locals: {project: project}

app/views/projects/_form.html.haml
= form_for(project) do |f|
  %h3
    Project Details:
  .row
    .col
      = f.label :title
      %br
      = f.text_field :title
    .col
      = f.label :category
      %br
      = f.select :category, options_for_select(Project.valid_categories, project.category)
    .col
      = f.label :modifier
      %br
      = f.text_field :modifier
    .col
      = f.label :handle
      %br
      = f.text_field :handle
  .row
    .col
      = f.label :description
      %br
      = f.text_area :description, size: '50x2'
    .col
      = f.label :priority
      %br
      = f.text_field :priority
  %h3
    Project Links/Attachments:
  .row
    .col
      = f.label :site_link
      %br
      = f.text_field :site_link
    .col
      = f.label :github_link
      %br
      = f.text_field :github_link
    .col
      = f.label :source_download
      = f.file_field :source_download, class: "btn btn-info"
      - if project.persisted? && project.source_download.present?
        .btn.btn-info
          = link_to "Delete Source", delete_attachment_path(id: project.id, attachment: "source_download"), method: :post
        .btn.btn-info
          = link_to "Project Source", project.source_download.url, class: "source-link" if project.source_download.present?
  %h3
    Project Contents:
  .row
    .col
      = f.label :content
      %br
      = f.text_area :content, size: '75x10', id: "markdown-input"
      %br
      #see_preview.btn.btn-primary
        See Preview
    .col
      %label
        Content Preview:
      #preview
  :javascript
    $(document).ready(function(){
      function updatePreview(){
        MarkdownConverter.updatePreview();
      }
      MarkdownConverter.updatePreview();
      $("#see_preview").click(updatePreview);
    });
  .row
    = f.submit 'Save', class: "btn btn-success", style: "width: 100%;"

app/views/projects/_index.html.haml
.frame
  - projects.each do |project_instance|
    = render partial: 'projects/project', locals: {project: project_instance}

app/views/projects/_project.html.haml
.project-frame.text-center
  = link_to project_path(project, source: params[:source]) do
    .project-title
      = project.title
    .project-modifier
      = project.modifier
    .project-description
      = project.description
  .project-links
    - if !project.course? && !project.site_link.blank?
      = link_to "Site", project.site_link, target: "_blank", class: "btn project-site-link"
    - if !project.github_link.blank?
      = link_to "Github", project.github_link, target: "_blank", class: "btn project-github-link"
    - if project.course? && !project.source_download.blank?
      = link_to "Source", project.source_download(:original, false), target: "_blank", class: "btn project-source-link"
  - if current_user
    .project-admin
      = link_to "Edit", edit_project_path(project)
      = link_to "Delete", project_path(project), method: 'DELETE'
%br

app/views/projects/courses.html.haml
.projects-frame
  = render partial: 'projects/display', locals: {projects: @projects}

app/views/projects/edit.html.haml
%h3
  Edit Project
= render partial: 'projects/form', locals: {project: @project}

= link_to "Back to Projects", projects_path

app/views/projects/hackathons.html.haml
.projects-frame
  = render partial: 'projects/display', locals: {projects: @projects}

app/views/projects/index.html.haml
%h4
  = link_to "Create New Project", new_project_path
%h3
  Existing Projects:
.projects-frame
  = render partial: 'projects/display', locals: {projects: @projects}

app/views/projects/new.html.haml
%h3
  Add New Project
= render partial: 'projects/form', locals: {project: @project}

= link_to "Back to Projects", projects_path

app/views/projects/portfolio.html.haml
.projects-frame
  = render partial: 'projects/display', locals: {projects: @projects}

app/views/projects/show.html.haml
.project-show-frame
  .project-details-frame
    .project-title.text-center
      = @project.title
  - if !@project.content.blank?
    .project-content
      = PersonalSite::MARKDOWN.render(@project.content).html_safe
  %br
  %br
  - if params[:source]
    - if params[:source] == "ADMIN"
      = link_to "Back to All Projects", projects_path
    - if params[:source] == "COURSE"
      = link_to "Back to Course Projects", courses_path
    - if params[:source] == "HACKATHON"
      = link_to "Back to Hackathon Projects", hackathons_path
    - if params[:source] == "PERSONAL"
      = link_to "Back to Personal Projects", portfolio_path