config/routes.rb
PersonalSite::Application.routes.draw do

  root 'pages#index'

  match "/about", to: "pages#about", as: :about, via: :get
  match "/education", to: "pages#education", as: :education, via: :get
  match "/courses", to: "projects#courses", as: :courses, via: :get
  match "/hackathons", to: "projects#hackathons", as: :hackathons, via: :get
  match "/portfolio", to: "projects#portfolio", as: :portfolio, via: :get
  match "/blog", to: "posts#index", as: :blog, via: :get
  match "/miscellaneous", to: "pages#miscellaneous", as: :miscellaneous, via: :get

  match "/github", to: redirect("https://github.com/RochesterinNYC"), as: :github, via: :get
  match "/linkedin", to: redirect("http://www.linkedin.com/in/jamesrwen"), as: :linkedin, via: :get
  match "/twitter", to: redirect("https://twitter.com/RochesterinNYC"), as: :twitter, via: :get
  match "/soundcloud", to: redirect("https://soundcloud.com/james-rochester-wen"), as: :soundcloud, via: :get

  resources :projects
  resources :posts
  resources :uploads

  get '/login', to: 'sessions#new', :as => "login"
  post '/verify', to: 'sessions#create', :as => 'verify'
  post '/logout', to: 'sessions#destroy', :as => 'logout'

  post '/markdown', to: 'projects#markdown', :as => 'markdown'
  post '/delete_attachment', to: 'projects#delete_attachment', :as => 'delete_attachment'
  post '/delete_file', to: 'uploads#delete_file', :as => 'delete_file'

end

app/models/upload.rb
class Upload < ActiveRecord::Base

  validates :handle, presence: true

  has_attached_file :file, url: "/uploads/:basename_:style.:extension", styles: { :thumbnail => "100x100>", :regular => "300x300>" }

  [:file].each do |attachment|
    define_method("#{attachment}_delete".to_sym) { self.send("#{attachment}=", nil); self.save! }
  end

  def delete_attachment(attachment)
    self.send("#{attachment}_delete")
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  before_filter :get_upload, only: [:delete_file, :destroy, :edit, :show, :update]
  before_filter :require_user, only: [:create, :delete_file, :destroy, :edit, :index, :new, :show, :update]

  respond_to :html, :json

  def create
    @upload = Upload.create(upload_params)
    if @upload.save
      redirect_to upload_path(@upload)
    else
      respond_with(@upload) do |format|
        format.json { render json: @upload.errors, status: :unprocessable_entity }
        format.html { render :new }
      end
    end
  end

  def delete_file
    @upload.delete_attachment('file')
    redirect_to edit_upload_path(@upload)
  end


  def destroy
    @upload.destroy
    redirect_to uploads_path
  end

  def edit
  end

  def index
    @uploads = Upload.order('created_at').all
  end

  def new
    @upload = Upload.new
  end

  def show
  end

  def update
    if @upload.update_attributes(upload_params)
      render :show
    else
      render :edit
    end
  end

  protected
  def get_upload
    @upload = Upload.find(params[:id])
  end

  private
  def upload_params
    params.require(:upload).permit(:description, :handle, :file, :file_file_name)
  end

end

app/views/uploads/_display.html.haml
- uploads.each do |upload|
  = render partial: 'uploads/upload', locals: {upload: upload}

app/views/uploads/_form.html.haml
= form_for(upload) do |f|
  %h3
    Upload Details:
  .row
    .col
      = f.label :handle
      %br
      = f.text_field :handle
    .col
      = f.label :description
      %br
      = f.text_area :description, size: '50x2'
  %h3
    Upload File:
  .row
    .col
      = f.label :file
      = f.file_field :file, class: "file-input btn btn-info"
      - if upload.persisted? && upload.file.present?
        .btn.btn-info
          = link_to "Delete File", delete_file_path(id: upload.id), method: :post
        = link_to(image_tag(upload.file.url(:thumbnail)), upload.file.url)
  .row
    = f.submit 'Save', class: "btn btn-success", style: "width: 100%;"

app/views/uploads/_upload.html.haml
.upload-frame.text-center
  = link_to upload_path(upload) do
    .upload-handle
      = upload.handle
    .upload-description
      = upload.description
    .upload-file-name
      = upload.file_file_name
  .upload-thumbnail
    - if upload.file.present?
      = link_to(image_tag(upload.file.url(:thumbnail)), upload.file.url)
  .upload-admin
    = link_to "Edit", edit_upload_path(upload)
    = link_to "Delete", upload_path(upload), method: 'DELETE'
%br

app/views/uploads/edit.html.haml
%h3
  Edit Upload
= render partial: 'uploads/form', locals: {upload: @upload}

= link_to "Back to Uploads", uploads_path

app/views/uploads/index.html.haml
%h4
  = link_to "Create New Upload", new_upload_path
%h3
  Existing Uploads:
.uploads-frame
  = render partial: 'uploads/display', locals: {uploads: @uploads}

app/views/uploads/new.html.haml
%h3
  Add New Upload
= render partial: 'uploads/form', locals: {upload: @upload}

= link_to "Back to Uploads", uploads_path

app/views/uploads/show.html.haml
.upload-show-frame
  .upload-details-frame
    .upload-handle.text-center
      = @upload.handle
    .upload-description.text-center
      = @upload.description
  - if !@upload.file.blank?
    .upload-file-name.text-center
      = @upload.file_file_name
    .upload-file-url.text-center
      = @upload.file.url  
    = link_to(image_tag(@upload.file.url(:original)), @upload.file.url)
  - else
    %h4.text-center
      No attachment.
  %br