config/routes.rb
PersonalSite::Application.routes.draw do

  root 'pages#index'

  match "/about", to: "pages#about", as: :about, via: :get
  match "/education", to: "pages#education", as: :education, via: :get
  match "/courses", to: "projects#courses", as: :courses, via: :get
  match "/hackathons", to: "projects#hackathons", as: :hackathons, via: :get
  match "/portfolio", to: "projects#portfolio", as: :portfolio, via: :get
  match "/blog", to: "posts#index", as: :blog, via: :get
  match "/miscellaneous", to: "pages#miscellaneous", as: :miscellaneous, via: :get

  match "/github", to: redirect("https://github.com/RochesterinNYC"), as: :github, via: :get
  match "/linkedin", to: redirect("http://www.linkedin.com/in/jamesrwen"), as: :linkedin, via: :get
  match "/twitter", to: redirect("https://twitter.com/RochesterinNYC"), as: :twitter, via: :get
  match "/soundcloud", to: redirect("https://soundcloud.com/james-rochester-wen"), as: :soundcloud, via: :get

  resources :projects
  resources :posts
  resources :uploads

  get '/login', to: 'sessions#new', :as => "login"
  post '/verify', to: 'sessions#create', :as => 'verify'
  post '/logout', to: 'sessions#destroy', :as => 'logout'

  post '/markdown', to: 'projects#markdown', :as => 'markdown'
  post '/delete_attachment', to: 'projects#delete_attachment', :as => 'delete_attachment'
  post '/delete_file', to: 'uploads#delete_file', :as => 'delete_file'

end

app/views/layouts/_initialize_js.html.haml
:javascript
  $(document).ready(function(){
    SidebarManager.initializeNav();
  }); 

app/views/layouts/_navigation.html.haml
%header#vertical-nav

  = link_to "James Wen", root_path, class: "nav-link"
  = link_to "Home", root_path, class: "nav-link home-link"
  = link_to "Admin Dashboard", projects_path, class: "nav-link projects-link" if current_user
  = link_to "About", about_path, class: "nav-link about-link"
  = link_to "Education", education_path, class: "nav-link education-link"
  = link_to "Personal Portfolio", portfolio_path, class: "nav-link portfolio-link"
  = link_to "Course Projects", courses_path, class: "nav-link courses-link"
  = link_to "Hackathons", hackathons_path, class: "nav-link hackathons-link"
  = link_to "Blog", posts_path, class: "nav-link posts-link"
  = link_to "Uploads", uploads_path, class: "nav-link uploads-link" if current_user
  = link_to "Logout", logout_path, method: 'post', class: "nav-link" if current_user
  #social-links
    = link_to image_tag("github-icon.png"), github_path, target: "_blank"
    = link_to image_tag("linkedin-icon.png"), linkedin_path, target: "_blank"
    = link_to image_tag("twitter-icon.png"), twitter_path, target: "_blank"
    = link_to image_tag("soundcloud-icon.png"), soundcloud_path, target: "_blank"
    = mail_to PersonalSite::PERSONAL_EMAIL, image_tag("email-icon.png")

app/views/layouts/application.html.haml
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : "James Wen\'s Personal Site"
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Personal Site'}"}
    = favicon_link_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = analytics_init if Rails.env.production?
  %body
    = render 'layouts/navigation'
    .content.text-center
      .frame
        - if !@title.blank?
          %h3.container.text-center
            = @title
        = yield
      .copyright.text-center
        ©
        = Date.today.strftime("%B")
        2014 - James Wen
    = render 'layouts/initialize_js'
    